### ISSUE TITLE
no information feedback on the site with frontend

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [ming08108/EtherPool-Frontend#1]
hi, i got "updated shares" on console.log, but nothing appears to update an idea to find why ?

Last payout: Last Payout Thu, 01 Jan 1970 00:00:00 GMT ext...

miner working on pool since 1hour

thanks!

**Comment by ming08108** [comment]
Are you running redis and do you have all the correct config files setup?

**Comment by VeilleurTrytoFix** [comment]
redis is runing, it already turns to other current application

maybe "path:" in config.js must be used how?

**Comment by ming08108** [comment]
"Last payout: " is the last time the payment script has been run. Can you see any miners on the main page? That is the function of the "updated shares" message.

**Comment by VeilleurTrytoFix** [comment]
Total Pool Hashrate 0 Mh/s
Total Pool Balance  0
Total Pool Shares 0
Thu, 01 Jan 1970 00:00:00 GMT

miner start

ethminer -F 10.0.0.50:8079/adresse/30 -G

**Comment by VeilleurTrytoFix** [comment]
ethServer : {
        host: '10.0.0.50',
        path: '/',
        //since we are listening on a custom port, we need to specify it by hand
        port: '8079',
        //This is what changes the request to a POST request
        method: 'POST'
    },

**Comment by ming08108** [comment]
Did you configure a redis password?

**Comment by VeilleurTrytoFix** [comment]
no password is requiered for redis

local geth rpc config

geth --rpc --rpcaddr "10.0.0.50" --rpcport 8079 console

**Comment by VeilleurTrytoFix** [comment]
i leave redis Password blank

redisPassword : ""

geth version
Geth
Version: 1.3.3
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

**Comment by VeilleurTrytoFix** [comment]
Still no information feedback on the frontend, I do not find solutions

**Comment by ming08108** [comment]
Where are you mining to? Are you also running https://github.com/ming08108/EtherPool?

**Comment by VeilleurTrytoFix** [comment]
i'm mining on local pool, etherpool is on

_etherpool.config_

module.exports = {

```
//This is where you setup geth rpc to listen on
ethServer : {
    host: '10.0.0.50',
    path: '/',
    //since we are listening on a custom port, we need to specify it by hand
    port: '8079',
    //This is what changes the request to a POST request
    method: 'POST'
},

redisPassword : "",

//Your pool coinbase address here
poolAddress : "pooladresse"
```

};

**Comment by ming08108** [comment]
Are you mining directly to the geth node? If so you need to be running https://github.com/ming08108/EtherPool and your miner needs to be finding shares. You also need to specify a poolAddress.

**Comment by VeilleurTrytoFix** [comment]
yes mining with geth  : geth --rpc --rpcaddr "10.0.0.50" --rpcport 8079 console

i dont know what im doing wrong

**Comment by VeilleurTrytoFix** [comment]
From console
Uncaught Error: Bootstrap's JavaScript requires jQuery(anonymous function) @ bootstrap.min.js:6

**Comment by ming08108** [comment]
Can you confirm that you are mining on port 6555 and not directly to the local geth node?

**Comment by VeilleurTrytoFix** [comment]
why 6555 port ?

**Comment by keepthefaya** [comment]
during npm install for Etherpool (not frontend)

1190 silly fetchPackageMetaData  error for ethereum-tests@git+https://github.com/ethereum/tests.git { [Error: EISDIR, read] errno: 28, code: 'EISDIR' }

**Comment by VeilleurTrytoFix** [comment]
it work when mining on 6555 port, I do not understand what has this to do the port :octopus:

**Comment by ming08108** [comment]
You need to mine to the https://github.com/ming08108/EtherPool. This is how the system logs the shares. By default the share server defaults to 6555.

https://github.com/ming08108/EtherPool/blob/master/run.js#L42

This acts like a proxy between the miner and the geth node so the system can log the shares. 

Did you eventually get it working?

**Comment by VeilleurTrytoFix** [comment]
I thank you for your explanation it works !

**Comment by ming08108** [comment]
You are very welcome. I am gonna close this issue. Let me know if you need anything else.
